name: wsgrpc
description: A new flutter package project.
version: 0.0.1
author: tsangpo <tsangpozheng@gmail.com>
homepage: https://github.com/tsangpo

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http2: ^1.0.0
  grpc: ^1.0.2
  # grpc: ^2.0.0+1
  protobuf: ^0.13.12

dev_dependencies:
  test: ^1.5.1
