name: wsgrpc
description: A dart client for wsgrpc. Using Websocket as transport of grpc will make client stream and server stream call available for browser scripts.
version: 2.0.3
homepage: https://github.com/tsangpo/wsgrpc-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http2: ^2.0.0
  grpc: ^3.0.0
  protobuf: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4