name: wsgrpc
description: A new flutter package project.
version: 0.0.3
author: tsangpo <tsangpozheng@gmail.com>
homepage: https://github.com/tsangpo

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http2: ^2.0.0
  grpc: ^3.0.0
  protobuf: ^2.0.0

dev_dependencies:
  test: ^1.5.1
